apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-app-virtualservice
  namespace: sample-app
spec:
  hosts:
    - "sample-app.io"
  gateways:
    - istio-system/sample-app-gateway
  http:
    - route:
        - destination:
            host: sample-app.sample-app
            port:
              number: 80