apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-worker
  name: nginx-worker
  namespace: hpa-test
spec:
  #replicas: 2 # managed by HPA
  selector:
    matchLabels:
      app: nginx-worker
  template:
    metadata:
      labels:
        app: nginx-worker
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "30m"
        ports:
        - containerPort: 80